version: "3.8"

services:
  mongoDB:
    image: "mongo"

    volumes:
      - data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: ty
      MONGO_INITDB_ROOT_PASSWORD: secret

    ports:
      - "27017:27017"

  backend:
    build: ./backend

    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules

    environment:
      MONGODB_USERNAME: ty
      MONGODB_PASSWORD: secret

    ports:
      - "80:80"

    depends_on:
      - mongoDB

  frontend:
    build: ./frontend

    volumes:
      - ./frontend/src:/app/src

    stdin_open: true

    tty: true

    ports:
      - "3000:3000"

    depends_on:
      - backend

volumes:
  data:
  logs:
